export { default as Home } from "./Home/Home";
export { default as Login } from "./Login/Login";
export { default as Register } from "./Register/Register";
export { default as Movie } from "./Movies/Movie";
export { default as Movies } from "./Movies/Movies";
export { default as Categories } from "./Categories/Categories";
export { default as Category } from "./Categories/Category";
export { default as Favorites } from "./Favorites/Favorites";
export { default as Account } from "./User/Account";
