export const types = {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  GET_MOVIES: "GET_MOVIES",
  GET_MOVIE: "GET_MOVIE",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORY: "GET_CATEGORY",
  ADD_MOVIE: "ADD_MOVIE",
  ADD_CATEGORY: "ADD_CATEGORY",
  DELETE_MOVIE: "DELETE_MOVIE",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  UPDATE_MOVIE: "UPDATE_MOVIE",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
};
