export const types = {
  SET_ERROR: "SET_ERROR",
  SET_USER: "SET_USER",
  LOG_OUT: "LOG_OUT",
  USER_LOADED: "USER_LOADED",
  REGISTER: "REGISTER",
  GET_MOVIES: "GET_MOVIES",
  GET_MOVIE: "GET_MOVIE",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORY: "GET_CATEGORY",
  CATEGORIES_LOADED: "CATEGORIES_LOADED",
  MOVIES_LOADED: "MOVIES_LOADED",
};
