export const types = {
  app: {
    LOAD_APP: "LOAD_APP",
  },
  user: {
    SET_ERROR: "SET_ERROR",
    SET_TOKEN: "SET_TOKEN",
    SET_USER: "SET_USER",
    LOG_OUT: "LOG_OUT",
    UPDATE_USER: "UPDATE_USER",
    SET_FAVORITE_MOVIE: "SET_FAVORITE_MOVIE",
    SET_WATCHING: "SET_WATCHING",
    REGISTER: "REGISTER",
  },

  categories: {
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_CATEGORY: "GET_CATEGORY",
  },

  movies: {
    GET_MOVIES: "GET_MOVIES",
    GET_MOVIE: "GET_MOVIE",
    RESET_MOVIES: "RESET_MOVIES",
    GET_USER_FAVORITE_MOVIES: "GET_USER_FAVORITE_MOVIES",
    GET_MOVIES_IN_CATEGORY: "GET_MOVIES_IN_CATEGORY",
  },

  header: {
    SET_USER_DROPDOWN: "SET_USER_DROPDOWN",
    SET_SEARCH: "SET_SEARCH",
    SET_MENU_MOBILE: "SET_MENU_MOBILE",
  },

  search: {
    GET_SEARCH_MOVIES: "GET_SEARCH_MOVIES",
    RESET_SEARCH: "RESET_SEARCH",
  },
};
