export const types = {
  user: {
    SET_ERROR: "SET_ERROR",
    SET_TOKEN: "SET_TOKEN",
    SET_USER: "SET_USER",
    LOG_OUT: "LOG_OUT",
    USER_LOADED: "USER_LOADED",
    REGISTER: "REGISTER",
  },

  categories: {
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_CATEGORY: "GET_CATEGORY",
    CATEGORIES_LOADING: "CATEGORIES_LOADING",
  },

  movies: {
    GET_MOVIES: "GET_MOVIES",
    GET_MOVIE: "GET_MOVIE",
    MOVIES_LOADING: "MOVIES_LOADING",
  },

  header: {
    SET_USER_DROPDOWN: "SET_USER_DROPDOWN",
    SET_SEARCH: "SET_SEARCH",
    SET_MENU_MOBILE: "SET_MENU_MOBILE",
  },

  search: {
    GET_SEARCH_MOVIES: "GET_SEARCH_MOVIES",
    RESET_SEARCH: "RESET_SEARCH",
  },
};
